### ISSUE TITLE
Tudat on eudoxos: unsupported GCC version for nlohmann/json

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#365] opened 2018-04-06 11:24 UTC
Hello everyone!! I am trying to install TUDAT in the student server 'eudoxos'. I was successful in installing the Qt creator and when I was at 98% of building the TUDAT libraries, I got the following error message:
[Server_ compilation_error.txt](https://github.com/Tudat/tudat/files/1883700/Server_.compilation_error.txt)
I followed the instructions given in the link: https://github.com/nlohmann/json#supported-compilers
I tried all the possible compiler versions for the linux OS (GCC, Clang) but the same error repeated.

**Comment by magnific0** [comment] 2018-04-06 11:27
Can you report which version of the compiler is on the server?

See: http://tudat.tudelft.nl/installation/troubleshooting/commandLineTools.html#verify-installation-of-cmake-and-compiler

**Comment by Pugazhenthi-Sivasankar** [comment] 2018-04-06 11:38
I entered the commands as given and got the following output:
[Cmake_compiler_version.txt](https://github.com/Tudat/tudat/files/1883753/Cmake_compiler_version.txt)

**Comment by magnific0** [comment] 2018-04-06 11:45
Your gcc version is 4.8, while "JSON for Modern C++" [requires](https://github.com/nlohmann/json#supported-compilers) 4.9 or higher. In fact 4.9 is also the recommended minimum for Tudat (although 4.8 can be made to work).

So unfortunately, the problem is with the system and not with the Tudat code. To fix this you should talk to the system administrator and see if it is possible to update gcc to a later version.

**Comment by Pugazhenthi-Sivasankar** [comment] 2018-04-06 11:47
Thank you for the suggestion!

**Comment by magnific0** [comment] 2018-04-06 11:51
You're welcome. I think it will be to the benefit of all students if the server got updated. As this doesn't pertain to the code, I'm closing the issue. But reply here anyway if the situation on eudoxos changes.

**Closed by magnific0** 2018-04-06 11:51 UTC

**Comment by Pugazhenthi-Sivasankar** [comment] 2018-05-01 15:06
This is a screenshot of the compiler version that I have in the Qt creator in the eudoxos student server:
![avail_server_compiler](https://user-images.githubusercontent.com/25662615/39478156-e10d9cc2-4d61-11e8-90b2-a88c3e9cdc58.jpg)
Is this compiler sufficient?

**Comment by DominicDirkx** [comment] 2018-05-02 07:33
I don't know, but it would indeed be the first thing I'd try. Run it, and see what it does. If it doesn't use the correct compiler, start adding some output messages to the compiler.cmake to figure out what's happening

**Comment by Pugazhenthi-Sivasankar** [comment] 2018-05-02 07:53
This is a screenshot of the compiler version that I have in the Qt creator in the eudoxos student server:
![avail_server_compiler](https://user-images.githubusercontent.com/25662615/39478156-e10d9cc2-4d61-11e8-90b2-a88c3e9cdc58.jpg)
Is this compiler sufficient?
