### ISSUE TITLE
Failed untit test (JsonInterfaceDeserialization)

### ISSUE THREAD

**Issue by FransMichielsen** [Tudat/tudat#303] opened 2017-11-21 17:03 UTC
[LastTest.log](https://github.com/Tudat/tudat/files/1492139/LastTest.log)

The failed unit test is 190:test_JsonInterfaceDeserialization

My OS is Windows 10

**Comment by magnific0** [comment] 2017-11-21 17:23
This is a duplicate of issue #275 and was solved. Please pull the latest version of Tudat from GitHub.

**Closed by magnific0** 2017-11-21 17:23 UTC
