### ISSUE TITLE
Failed Unit Tests Windows

### ISSUE THREAD

**Issue by FloorMelman** [Tudat/tudat#134] opened 2017-02-17 09:23 UTC
[LastTest.txt](https://github.com/Tudat/tudat/files/782763/LastTest.txt)

**Comment by DominicDirkx** [comment] 2017-02-17 09:51
This is a duplicate of an error that has occured for a number of users, solution will be posted in #129 when ready. 

This error does not indicate anything wrong with the code, but seems to be a result of Windows not allowing Qt to run executables with 'setup' or 'updater' in there name.

**Closed by DominicDirkx** 2017-02-17 09:51 UTC
