### ISSUE TITLE
System boost used in Ubuntu

### ISSUE THREAD

**Issue by FrankHogervorst** [Tudat/tudat#203] opened 2017-06-01 15:25 UTC
I recently switched to Ubuntu 16.04 with gcc 5.4.0. Running main CMake works, but now I am trying to build all libraries and get the errors as shown below, did boost not install correctly?
Could it be related to https://github.com/Tudat/tudat/issues/152? 
```
[ 87%] Linking CXX executable /home/frank/tudatBundle/tudat/bin/unit_tests/test_AerodynamicMomentAndAerodynamicForce
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::unwind_extra_block(bool)':
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockEb[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE18unwind_extra_blockEb]+0x2c): undefined reference to `boost::re_detail_106000::put_mem_block(void*)'
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106000::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106000::re_set_long<unsigned int> const*, boost::re_detail_106000::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool)':
streamFilters.cpp:(.text._ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x12a): undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
streamFilters.cpp:(.text._ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb[_ZN5boost16re_detail_10600016re_is_set_memberIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEjEET_SH_SH_PKNS0_11re_set_longIT2_EERKNS0_10regex_dataIT0_T1_EEb]+0x2f5): undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find_imp()':
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0xa): undefined reference to `boost::re_detail_106000::get_mem_block()'
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x151): undefined reference to `boost::re_detail_106000::verify_options(unsigned int, boost::regex_constants::_match_flags)'
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x190): undefined reference to `boost::re_detail_106000::put_mem_block(void*)'
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE8find_impEv]+0x32d): undefined reference to `boost::re_detail_106000::put_mem_block(void*)'
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `bool boost::regex_search<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)':
streamFilters.cpp:(.text._ZN5boost12regex_searchIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISB_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SJ_RNS_13match_resultsISJ_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsESJ_[_ZN5boost12regex_searchIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISB_EEEcNS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEbT_SJ_RNS_13match_resultsISJ_T0_EERKNS_11basic_regexIT1_T2_EENS_15regex_constants12_match_flagsESJ_]+0x123): undefined reference to `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `void boost::re_detail_106000::raise_error<boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > >(boost::regex_traits_wrapper<boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::error_type)':
streamFilters.cpp:(.text._ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE[_ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE]+0xb2): undefined reference to `boost::re_detail_106000::raise_runtime_error(std::runtime_error const&)'
streamFilters.cpp:(.text._ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE[_ZN5boost16re_detail_10600011raise_errorINS_20regex_traits_wrapperINS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEEEEEvRKT_NS_15regex_constants10error_typeE]+0xe0): undefined reference to `boost::re_detail_106000::get_default_error_string(boost::regex_constants::error_type)'
/home/frank/tudatBundle/tudat/lib/libtudat_input_output.a(streamFilters.cpp.o): In function `boost::re_detail_106000::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::extend_stack()':
streamFilters.cpp:(.text._ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv[_ZN5boost16re_detail_10600012perl_matcherIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISC_EEENS_12regex_traitsIcNS_16cpp_regex_traitsIcEEEEE12extend_stackEv]+0x18): undefined reference to `boost::re_detail_106000::get_mem_block()'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/frank/tudatBundle/tudat/bin/unit_tests/test_AerodynamicMomentAndAerodynamicForce] Error 1
make[1]: *** [tudat/Tudat/Astrodynamics/Aerodynamics/CMakeFiles/test_AerodynamicMomentAndAerodynamicForce.dir/all] Error 2
make: *** [all] Error 2
tudat/Tudat/Astrodynamics/Aerodynamics/CMakeFiles/test_AerodynamicMomentAndAerodynamicForce.dir/build.make:121: recipe for target '/home/frank/tudatBundle/tudat/bin/unit_tests/test_AerodynamicMomentAndAerodynamicForce' failed
CMakeFiles/Makefile2:324: recipe for target 'tudat/Tudat/Astrodynamics/Aerodynamics/CMakeFiles/test_AerodynamicMomentAndAerodynamicForce.dir/all' failed
Makefile:138: recipe for target 'all' failed
16:51:17: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop Qt 5.9.0 GCC 64bit)
When executing step "CMake Build"
16:51:17: Elapsed time: 00:07.
```

**Comment by DominicDirkx** [comment] 2017-06-01 19:05
I'm pretty sure this is because you're using boost 1.53 (?). Change it to boost 1.60 and it should work

**Comment by FrankHogervorst** [comment] 2017-06-02 07:35
I am already using boost 1.60

**Comment by FrankHogervorst** [comment] 2017-06-02 09:59
Maybe the solution is to use boost 1.63? (due to incompatibility issues between compiler and boost)

**Comment by DominicDirkx** [comment] 2017-06-02 10:34
set(BoostVersion 1.63.0)
set(BoostSHA1 9f1dd4fa364a3e3156a77dc17aa562ef06404ff6)

**Comment by FrankHogervorst** [comment] 2017-06-02 11:38
Too bad, this did not fix the errors with both gcc and clang compiler.

**Comment by DominicDirkx** [comment] 2017-06-02 13:11
Hi Frank, 

I'm able to reproduce the error with GCC 5.3 and boost 1.60, but if I delete my built folder, CMakeCache and boost folders (the last one shouldn't be necessary, but better safe than sorry), update the top-level cmake lists to use boost 1.63, all works well (with GCC). Are you sure no old settings/files were used when you updated boost?

Dominic

**Comment by FrankHogervorst** [comment] 2017-06-02 13:52
I followed you instructions, deleted built folder CMakeCache and boost folders and selected boost 1.63. 
This did not work, but I did found out I use gcc 5.4. This must be the problem at hand. How can I safely downgrade to 5.3?

**Comment by DominicDirkx** [comment] 2017-06-02 14:03
Sorry, my bad, I also have gcc 5.4. Have you tried to delete the folder I mentioned above, and use clang (which version do you have?) with boost 1.60?

**Comment by FrankHogervorst** [comment] 2017-06-02 14:26
CMakeCache is located inside the built folder right? 

clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

**Comment by DominicDirkx** [comment] 2017-06-04 20:13
Hi Frank,

Yes, indeed, CMakeCache.txt is in the build folder. Also, there is a CMakeLists.txt.user file in the same folder as the top-level CMakeLists.txt file. To make sure no settings from any old build are used, you can try deleting this as well,

Dominic

**Comment by FrankHogervorst** [comment] 2017-06-05 10:29
I still have the same problems, I did the following:
- Deleted CMakeList.txt.user 
- Deleted CMakeCache
- Deleted build folder
- Deleted boost folder
- Rebuild using boost 1.63 with gcc and clang
- Did the same thing as above but for boost 1.60

It does however seems to use some boost items outside the tudat folder which are boost 1.58:
 **/usr/lib/x86_64-linux-gnu/libboost_filesystem.a;**optimized;**/usr/lib/x86_64-linux-gnu/libboost_date_time.a;** debug;/home/frank/tudatBundle/boost/stage/lib/libboost_date_time-mt.a;optimized;**/usr/lib/x86_64-linux-gnu/libboost_system.a** ;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_system-mt.a;optimized; **/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a;** debug;/home/frank/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a;optimized; **/usr/lib/x86_64-linux-gnu/libboost_filesystem.a;** debug;/home/frank/tudatBundle/boost/stage/lib/libboost_filesystem-mt.a;optimized; **/usr/lib/x86_64-linux-gnu/libboost_regex.a;** debug;/home/frank/tudatBundle/boost/stage/lib/libboost_regex-mt.a

**Comment by DominicDirkx** [comment] 2017-06-05 13:56
That's odd, but it does explain the problem you're having. How and where exactly did you print these libraries?

**Comment by magnific0** [comment] 2017-06-06 06:59
@FrankHogervorst it is trying to use your system libraries instead. How old is your tudatBundle? Recently we have made a few small modifications to add_boost.cmake, which should prevent this behaviour.

Can you tell which version of the bundle you have?

If you are still on the old one, you can just copy in [this line](https://github.com/Tudat/tudatBundle/blob/master/external/CMake/add_boost.cmake#L78) in your main CMakeLists.txt. Just below [this line](https://github.com/Tudat/tudatBundle/blob/master/CMakeLists.txt#L57) should do.

**Comment by FrankHogervorst** [comment] 2017-06-06 09:33
@DominicDirkx the libraries are printed inside `/home/frank/tudatBundle/tudat/Tudat/Mathematics/BasicMathematics/CMakeLists.txt`
with 
`message(STATUS "Boost libraries:  ${Boost_LIBRARIES}")`

@magnific0 Latest tudatBundle commit:   4edcd331d347cb169dee570221c82730600c43c1

files in boost/stage lib:
```
libboost_chrono-mt.a
libboost_chrono-mt.so
libboost_chrono-mt.so.1.60.0
libboost_chrono-mt.so.1.63.0
libboost_date_time-mt.a
libboost_date_time-mt.so
libboost_date_time-mt.so.1.60.0
libboost_date_time-mt.so.1.63.0
libboost_filesystem-mt.a
libboost_filesystem-mt.so
libboost_filesystem-mt.so.1.60.0
libboost_filesystem-mt.so.1.63.0
libboost_prg_exec_monitor-mt.a
libboost_prg_exec_monitor-mt.so
libboost_prg_exec_monitor-mt.so.1.60.0
libboost_prg_exec_monitor-mt.so.1.63.0
libboost_regex-mt.a
libboost_regex-mt.so
libboost_regex-mt.so.1.60.0
libboost_regex-mt.so.1.63.0
libboost_system-mt.a
libboost_system-mt.so
libboost_system-mt.so.1.60.0
libboost_system-mt.so.1.63.0
libboost_test_exec_monitor-mt.a
libboost_thread-mt.a
libboost_thread-mt.so
libboost_thread-mt.so.1.60.0
libboost_thread-mt.so.1.63.0
libboost_timer-mt.a
libboost_timer-mt.so
libboost_timer-mt.so.1.60.0
libboost_timer-mt.so.1.63.0
libboost_unit_test_framework-mt.a
libboost_unit_test_framework-mt.so
libboost_unit_test_framework-mt.so.1.60.0
libboost_unit_test_framework-mt.so.1.63.0
```

This is the output from the boost locations:
```
FILESYSTEM: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_filesystem.a;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_filesystem-mt.a
-- SYSTEM: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_system.a;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_system-mt.a
-- THREAD: ON - /home/frank/tudatBundle/boost/stage/lib/libboost_thread-mt.so
-- REGEX: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_regex.a;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_regex-mt.a
-- DATE_TIME: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_date_time.a;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_date_time-mt.a
-- UNIT_TEST_FRAMEWORK: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a;debug;/home/frank/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a
```

**Comment by DominicDirkx** [comment] 2017-06-06 09:45
Can you confirm that the line [here](https://github.com/Tudat/tudatBundle/blob/master/external/CMake/add_boost.cmake#L78):

set(Boost_NO_SYSTEM_PATHS ON)

is indeed correct on your version?

**Comment by FrankHogervorst** [comment] 2017-06-06 09:48
Yes it is indeed correct on my version

**Comment by magnific0** [comment] 2017-06-06 11:03
Normally it shouldn't ignore the flag like this. Also you have a mix between static and dynamic libraries. No wonder really that it is failing. You could try uninstalling any libboost packages using the "Software Centre", just to see if this makes a difference. Given of course that no packages rely on these.

**Comment by FrankHogervorst** [comment] 2017-06-06 11:08
How can I verify whether any packages rely on these libboost packages?

**Comment by DominicDirkx** [comment] 2017-06-06 15:34
I'm not sure if you can... However, you can always reinstall the boost packages if you break anything. I recently installed ubuntu 16.04 and don't have system boost libraries at all. Uninstalling the system boost is fairly straightforward:

https://askubuntu.com/questions/397939/how-to-uninstall-boost-1-49-and-install-boost-1-54-in-ubuntu

**Comment by FrankHogervorst** [comment] 2017-06-07 09:24
This indeed fixes the boost problems. Thanks for the help!

**Comment by DominicDirkx** [comment] 2017-06-07 09:36
Great to hear it! I'm reopening this issue, because we should find a way to make everything work properly, even with the system boost present.

**Comment by magnific0** [comment] 2017-06-07 09:48
@FrankHogervorst as a general rule, if it let's you uninstall a package without complaining there are no dependencies on it.

However, we can not rely on everyone to not have boost installed on the system, so we should find a way to fix this. Would you be available on Friday to look at this together on your system?

**Comment by FrankHogervorst** [comment] 2017-06-07 09:54
Yes of course,  I am available on Friday untill 11:30 and I have a progress meeting with @DominicDirkx at 14:00 after which I have time to adress this issue.

**Comment by FrankHogervorst** [comment] 2017-06-07 12:36
This seems related, when building PaGMo problems it complains that there is a redefinition of a class, located in a system Eigen package. 

```
In file included from /home/frank/tudatBundle/pagmo/src/Eigen/Eigenvalues:35:0,
                 from /home/frank/tudatBundle/pagmo/src/Eigen/Dense:7,
                 from /home/frank/tudatBundle/pagmo/src/serialization.h:61,
                 from /home/frank/tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx/../PaGMOEx/Problems/earthMarsTransfer.h:20,
                 from /home/frank/tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx/Problems/earthMarsTransfer.cpp:17:
/home/frank/tudatBundle/pagmo/src/Eigen/src/misc/RealSvd2x2.h:19:6: error: redefinition of ‘template<class MatrixType, class RealScalar, class Index> void Eigen::internal::real_2x2_jacobi_svd(const MatrixType&, Index, Index, Eigen::JacobiRotation<RealScalar>*, Eigen::JacobiRotation<RealScalar>*)’
 void real_2x2_jacobi_svd(const MatrixType& matrix, Index p, Index q,
      ^
In file included from /usr/include/eigen3/Eigen/SVD:36:0,
                 from /usr/include/eigen3/Eigen/Geometry:15,
                 from /home/frank/tudatBundle/tudat/Tudat/Astrodynamics/BasicAstrodynamics/orbitalElementConversions.h:36,
                 from /home/frank/tudatBundle/tudatExampleApplications/libraryExamples/PaGMOEx/Problems/earthMarsTransfer.cpp:13:
/usr/include/eigen3/Eigen/src/SVD/JacobiSVD.h:405:6: note: ‘template<class MatrixType, class RealScalar, class Index> void Eigen::internal::real_2x2_jacobi_svd(const MatrixType&, Index, Index, Eigen::JacobiRotation<RealScalar>*, Eigen::JacobiRotation<RealScalar>*)’ previously declared here
 void real_2x2_jacobi_svd(const MatrixType& matrix, Index p, Index q,
```

**Comment by DominicDirkx** [comment] 2017-06-07 12:40
Sounds like it. For the compilation of which executable is this occuring? If it is the Tudat example, my guess is that Pagmo and Tudat detect different libraries.

**Comment by FrankHogervorst** [comment] 2017-06-07 12:41
Yes this is the `example_library_pagmo` inside the tudatExampleApplications

**Comment by DominicDirkx** [comment] 2017-06-07 12:51
I'm guessing that's it then: pagmo uses the system Eigen, while Tudat uses the one in the Tudat directory.

**Comment by magnific0** [comment] 2017-06-07 16:09
Let's meet after your meeting with Dominic then! 

Regarding the Eigen, we give PaGMO hints on where to look for it (i.e., our local version). Seems like this is also not working well then... :-)

**Comment by DominicDirkx** [comment] 2017-06-11 19:05
Any update on this issue after the in-person help?

**Comment by magnific0** [comment] 2017-06-12 07:08
**Update Boost**: nothing we tried prevented CMake from choosing system version of Boost instead if present. We double checked all flags etcetera, but no luck.

It is entirely possible that CMake (version 3.5.1 on Ubuntu 16.04) contains a bug in it's ```FindBoost.cmake``` or other the scripts that handle the ```NO_CMAKE_SYSTEM_PATH``` and/or ```NO_SYSTEM_ENVIRONMENT_PATH``` flags. At least [multiple discussions online](https://encrypted.google.com/search?q=Boost_NO_SYSTEM_PATHS+not+working) seems to suggest so. CMake version 3.8.0 on my system behaves well. I see only two possibilities here: (1) include our own ```FindBoost.cmake``` which we can control or (2) tell people to upgrade CMake to a version which works. One problem with (1) is that ```FindBoost.cmake``` hard-codes boost versions, which would require us to maintain the file. Solution (2) is usually not easy for users with a tightly controlled package manager.

**Update Eigen**: it turned out that when Eigen is installed on the system, Tudat prefers the system version, while PaGMO uses its packaged Eigen. On @FrankHogervorst system the We could prevent this from happening by setting:

     set(EIGEN3_INCLUDE_DIR "${PROJECTROOT}/eigen" CACHE PATH "Source directory of Eigen, by default choose the Eigen in the Tudat Bundle")

Tudat bundles Eigen 3.3.2. PaGMO also bundles Eigen 3.3.2. Ubuntu 16.04 installs 3.3~beta1-2, which conflicts with PaGMO's version, as demonstrated above. As a side note, I have 3.3.3 installed on my system (Arch Linux), which does not conflict with PaGMO's version when used. Still I think we should include the above line in our top-level ```CMakeLists.txt```.

**Comment by DominicDirkx** [comment] 2017-11-04 12:40
Hi Frank,

Could you add a note on this to the troubleshooting page?

**Comment by FrankHogervorst** [comment] 2017-11-07 12:35
This is added to the troubleshooting page, I'll keep the issue open since no fix has been found so far.

**Comment by DominicDirkx** [comment] 2018-06-05 09:58
Closing issue, point is highlighted on troubleshooting page.

**Closed by DominicDirkx** 2018-06-05 09:58 UTC
Labels: Linux, bug
