### ISSUE TITLE
Windows 10, got the same problem with the three units listed in blackboard

### ISSUE THREAD

**Issue by matteoserman** [Tudat/tudat#135] opened 2017-02-17 12:54 UTC
I've attached the pdf file since github didn't allow me to update txt file
[LastTest.pdf](https://github.com/Tudat/tudat/files/783231/LastTest.pdf)

**Comment by DominicDirkx** [comment] 2017-02-17 16:43
Duplicate of issue #129

**Closed by DominicDirkx** 2017-02-17 16:43 UTC
