### ISSUE TITLE
Error when building development branch

### ISSUE THREAD

**Issue by Pugazhenthi-Sivasankar** [Tudat/tudat#256] opened 2017-10-05 10:54 UTC
```
[ 93%] Linking CXX executable C:\Users\Pugazh\tudatBundle\tudat\bin\unit_tests\test_CustomStatePropagation.exe

cc1plus.exe: out of memory allocating 65536 bytes
tudat\Tudat\Astrodynamics\Propagators\CMakeFiles\test_CowellStateDerivative.dir\build.make:62: recipe for target 'tudat/Tudat/Astrodynamics/Propagators/CMakeFiles/test_CowellStateDerivative.dir/UnitTests/unitTestCowellStateDerivative.cpp.obj' failed
mingw32-make[2]: *** [tudat/Tudat/Astrodynamics/Propagators/CMakeFiles/test_CowellStateDerivative.dir/UnitTests/unitTestCowellStateDerivative.cpp.obj] Error 1
CMakeFiles\Makefile2:6171: recipe for target 'tudat/Tudat/Astrodynamics/Propagators/CMakeFiles/test_CowellStateDerivative.dir/all' failed
mingw32-make[1]: *** [tudat/Tudat/Astrodynamics/Propagators/CMakeFiles/test_CowellStateDerivative.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
[ 93%] Built target test_EnckeStateDerivative
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE[__ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tools.o): duplicate section `.rdata$_ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE[__ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
[ 93%] Built target test_CustomStatePropagation
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tools.o): duplicate section `.rdata$_ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE[__ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE[__ZTSN5boost6detail17sp_counted_impl_pINS_23basic_wrap_stringstreamIcEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(test_tree.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(unit_test_parameters.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE[__ZTSN5boost16exception_detail19error_info_injectorINS_17bad_function_callEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_unit_test_framework-mt.a(execution_monitor.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_17bad_function_callEEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt13runtime_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE[__ZTSN5boost16exception_detail19error_info_injectorISt11logic_errorEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTSN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt13runtime_errorEEEE]' has different size
C:/Users/Pugazh/tudatBundle/boost/stage/lib/libboost_regex-mt.a(regex.o): duplicate section `.rdata$_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE[__ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorISt11logic_errorEEEE]' has different size
[ 93%] Built target test_DependentVariableOutput
makefile:137: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
12:23:51: The process "C:\Qt\Tools\mingw492_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "Make"
```

**Comment by DominicDirkx** [comment] 2017-10-05 10:57
Hi, could you let me know which

- Operating system
- Compiler
- Boost version
- Tudat version (branch)

you are using? 

My first guess with this error is that it's a mismatch between boost and the compiler, which can be easily fixed by updating the top-level CMakeLists file (commenting the boost 1.53, and uncommenting the boost 1.60 lines).

Dominic

**Comment by DominicDirkx** [comment] 2017-10-05 13:38
Hi, I think the problem is that you're using multiple cores to compile, and are running out of RAM. Remove the -jX that have put as compile arguments, and try again.

**Comment by Pugazhenthi-Sivasankar** [comment] 2017-10-05 13:52
Dear Dominic,

                    The message was sent to you by Aleix from my account when he was working with MATLAB interface.



Thanks and regards,
Pugazh.

        -----------

Pugazhenthi Sivasankar,
Student number: 4414764,
M.Sc. Space Exploration,
Delft University of Technology,
The Netherlands.
________________________________

**Comment by DominicDirkx** [comment] 2017-10-05 14:40
Ok, that's fine. Let me know if the multi-core compilation was the issue,

Best,

Dominic

**Comment by DominicDirkx** [comment] 2017-10-12 08:08
Hi, 

Has the proposed fix corrected the problem? 

Dominic

**Comment by DominicDirkx** [comment] 2017-11-04 12:37
Since there has been no reply, and no-one has been able to reproduce this, I'm closing the issue. The symptoms indicate either wrong boost version/incomparible boost compilation or Windows multi-core compilation

**Closed by DominicDirkx** 2017-11-04 12:37 UTC
