### ISSUE TITLE
Failed unit test: test_JsonInterfaceDeserialization (Failed)

### ISSUE THREAD

**Issue by andreribeiro1996** [Tudat/tudat#302] opened 2017-11-21 13:38 UTC
Hello! The following test failed:
![failed test](https://user-images.githubusercontent.com/33599658/33075351-73411366-cec9-11e7-857d-ba5d4c561b86.PNG)

[LastTest.log](https://github.com/Tudat/tudat/files/1491508/LastTest.log)
[LastTestsFailed.log](https://github.com/Tudat/tudat/files/1491509/LastTestsFailed.log)

My operative system is Windows 10.

**Comment by magnific0** [comment] 2017-11-21 17:22
This is a duplicate of issue #275 and was solved. Please pull the latest version of Tudat from GitHub

**Closed by magnific0** 2017-11-21 17:22 UTC
