### ISSUE TITLE
Tests log

### ISSUE THREAD

**Issue by aleixpinardell** [Tudat/tudat#84] opened 2016-11-08 10:21 UTC
A few tests failed:
[LastTest.log.txt](https://github.com/Tudat/tudat/files/577852/LastTest.log.txt)

**Comment by DominicDirkx** [comment] 2016-11-08 11:59
Hi Aleix,

I've made come changes to the code that should make 4 out of the 5 unit tests pass correctly. The 5th one (RKF56) is a bit of a mystery for me for now. I will probably ask you for some specific extra output from this test in the coming week, to get the issue sorted.

**Comment by DominicDirkx** [comment] 2016-11-08 13:45
Hi Aleix,

Could you make the following changes to the RK56 unit test, run it, and post the output here?

Add the following to the include statements (after BOOST_TEST_MAIN):

#include <iostream>
#include <iomanip>

Add the following after the definition of the analytical solution  of the first test case (e.g. line 127):

    std::cout<<"Final time: "<<std::setprecision( 16 )<<integrator56.getCurrentIndependentVariable( )<<std::endl;
    std::cout<<"Final step size: "<<integrator56.getNextStepSize( )<<std::endl;
    std::cout<<"Final state: "<<numericalSolution.transpose( )<<std::endl;
    std::cout<<"Analytical state: "<<analyticalSolution.transpose( )<<std::endl;

Thanks!

**Comment by aleixpinardell** [comment] 2016-11-08 14:02
```
Starting /Users/aleix/Documents/tudatBundle/tudat/bin/unit_tests/test_RungeKuttaFehlberg56Integrator...
Running 4 test cases...
Final time: 4.999731425190508
Final step size: 0.002404559064947531
Final state:  2.693506250380319 0.8737042746150937
Analytical state:  2.694473468661085 0.8760327962563325
/Users/aleix/Documents/tudatBundle/tudat/Tudat/Mathematics/NumericalIntegrators/UnitTests/unitTestRungeKuttaFehlberg56Integrator.cpp:137: error in "test_RungeKuttaFehlberg56_Integrator_Fehlberg_Benchmark": absolute value of std::fabs( computedError( 0 ) ){0.00096721828076518079} exceeds 9.9999999999999998e-13
/Users/aleix/Documents/tudatBundle/tudat/Tudat/Mathematics/NumericalIntegrators/UnitTests/unitTestRungeKuttaFehlberg56Integrator.cpp:138: error in "test_RungeKuttaFehlberg56_Integrator_Fehlberg_Benchmark": absolute value of std::fabs( computedError( 1 ) ){0.0023285216412387566} exceeds 9.9999999999999998e-13
/Users/aleix/Documents/tudatBundle/tudat/Tudat/Mathematics/NumericalIntegrators/UnitTests/unitTestRungeKuttaFehlberg56Integrator.cpp:148: error in "test_RungeKuttaFehlberg56_Integrator_Fehlberg_Benchmark": check computedError( 0 ) / fehlbergError( 0 ) >= 0.0 failed [-9022558589.2274323 < 0]
/Users/aleix/Documents/tudatBundle/tudat/Tudat/Mathematics/NumericalIntegrators/UnitTests/unitTestRungeKuttaFehlberg56Integrator.cpp:152: error in "test_RungeKuttaFehlberg56_Integrator_Fehlberg_Benchmark": absolute value of std::fabs( computedError( 0 ) / fehlbergError( 0 ) ){9022558589.2274323} exceeds 3
/Users/aleix/Documents/tudatBundle/tudat/Tudat/Mathematics/NumericalIntegrators/UnitTests/unitTestRungeKuttaFehlberg56Integrator.cpp:153: error in "test_RungeKuttaFehlberg56_Integrator_Fehlberg_Benchmark": absolute value of std::fabs( computedError( 1 ) / fehlbergError( 1 ) ){10632518909.766012} exceeds 1

*** 5 failures detected in test suite "Master Test Suite"
/Users/aleix/Documents/tudatBundle/tudat/bin/unit_tests/test_RungeKuttaFehlberg56Integrator exited with code 201
```

**Comment by DominicDirkx** [comment] 2016-11-08 14:03
Perfect, thanks! The issue seems to be that the integrator is not propagating exactly to the final time (5.0), but is stopping at 4.999731425190508.

**Comment by DominicDirkx** [comment] 2016-11-08 14:17
Another test to nail down this issue:

In Tudat/Mathematics/NumericalIntegrators/numericalIntegrator.h on line 207 (between performIntegrationStep and stepSize =...) add the line:

`        std::cout<<"Times in loop: "<<intervalEnd - getCurrentIndependentVariable( )<<" "<<getNextStepSize( )<<" "<<atIntegrationIntervalEnd<<std::endl;
`

and run the test again. This will spit out a long list of numbers. If you could paste those into a text file and attach it here, I'll have another look,

Dominic

**Comment by aleixpinardell** [comment] 2016-11-08 14:36
[output.txt](https://github.com/Tudat/tudat/files/578403/output.txt)

**Comment by DominicDirkx** [comment] 2016-11-08 15:12
Hi Aleix,

Here's my first attempt at a fix for the problem,

Replace the statement:

```
            if( intervalEnd - getCurrentIndependentVariable( ) > std::fabs( stepSize ) *
                    ( 1.0 + std::numeric_limits< IndependentVariableType >::epsilon( ) ) )
```

On line 217-218 of the original numericalIntegrator.h with:


`if( std::fabs( intervalEnd - getCurrentIndependentVariable( ) ) > std::numeric_limits< IndependentVariableType >::epsilon( ) )`

Recompile and run the test. If it still fails, please attach the new output. Thanks for the help in sorting out this bug!

Dominic

**Comment by aleixpinardell** [comment] 2016-11-08 16:05
Still failing...
```
Final time: 5
Final step size: 1.178299241676518e-05
Final state:  2.694473468661329 0.8760327962562559
Analytical state:  2.694473468661085 0.8760327962563325
```
[output.txt](https://github.com/Tudat/tudat/files/578676/output.txt)

**Comment by aleixpinardell** [comment] 2016-11-08 16:07
I did the tests again and this time all are passed.

**Comment by DominicDirkx** [comment] 2016-11-09 09:05
Great! Thanks for the quick help in getting this issue sorted out. 

I'll post a decent explanation of the source of the bug here later today or tomorrow, and commit the required fix to the repository.

**Comment by DominicDirkx** [comment] 2016-11-09 12:08
A patch for the code has been committed. When you have time (or just the next time you update your code), could you get the latest code for the repository and check whether the problem is indeed fixed?

The issue was in the fact that the time step size was changed during the last time step, causing the last time step to be shorter than initially thought, terminating the integration just shy of the required final time. There was a check in the integrateTo function, but it was not robust enough to handle your specific case as well.

**Comment by aleixpinardell** [comment] 2016-11-09 12:26
Done

100% tests passed, 0 tests failed out of 126

**Comment by DominicDirkx** [comment] 2016-11-09 12:30
Awesome! Closing the issue.

**Closed by DominicDirkx** 2016-11-09 12:30 UTC
