### ISSUE TITLE
TLE File reader kepler elements

### ISSUE THREAD

**Issue by Reneh107** [Tudat/tudat#52] opened 2016-06-14 12:00 UTC
I have performed some test that uses the TLE file reader and observed that I don't get the same results when I use the kepler elements that tudat produces and converting it to cartesian coordinates compared to the output sgp4 produces when returning the initial state. 

I have not investigated this in great detail, so this is something to keep in mind if you want to use these kepler elements. Maybe there is something wrong in the conversion process.

**Comment by magnific0** [comment] 2016-12-07 09:24
The Tudat routine for this is rather crude and arguably just plainly wrong. As discussed with @mhaneveer this particular code should be removed as soon as a more proper solution in the form of an external library is implemented, see #103.

**Comment by magnific0** [comment] 2017-02-22 11:59
I think it is better to close the issue. The problem is noted and the solution should come in the form the addition of a SGP4 code to Tudat, see #103. Further discussion should take place there.

**Closed by magnific0** 2017-02-22 11:59 UTC
