### ISSUE TITLE
Boost linking error: undefined reference to `boost::[...]'. find_boost mixes local and system libraries.

### ISSUE THREAD

**Issue by jgutierrezahum** [Tudat/tudat#152] opened 2017-02-28 11:10 UTC
I have encountered some problems when building Tudat that seem to be related to boost. In particular, I got the error that can be seen in error1.txt

Apparently this could be due to using a quite new version of gcc (I run gcc 5.4 and Ubuntu 16.04). I thus changed the boost version to 1.60 on the CMakeLists file and then downloaded and installed this new version. Unfortunately, a new error appeared when trying to build Tudat (see error2.txt).

Besides, as suggested in [http://tudat.tudelft.nl/projects/tudat/wiki/Troubleshooting#22-Check-if-Boost-build-succesfully](url), I attach the following files:

- cmake_output.txt     showing the output of the cmake command
- version.hpp              showing the version for boost
- boost_libs.txt            showing the libraries installed with boost
- cmake-config.jam, project-config.jam, build_bootstrap.log and build_b2.log

These last two logs seem to throw an ERROR at the end.

[boost_issue.zip](https://github.com/Tudat/tudat/files/806524/boost_issue.zip)

**Comment by magnific0** [comment] 2017-02-28 14:26
Hi @jgutierrezahum, thanks for reporting the issue. Good to hear more people are running GNU/Linux! I have GCC 6.3.1 and am able to successfully use most boost versions, so I doubt the issue is related to your version. This is mainly a problem that we encounter with different versions of MinGW on Windows.

The errors are related to linking the Boost libraries to the Tudat applications. In your cmake_output.txt it mentions that it finds 1.58.0, which is quite strange as you have build 1.53 and 1.60. It looks like you have a version of Boost installed and it's finding that. 

This still doesn't fully explain the issue though. First, it should ignore any version of Boost on the system. Second, it wouldn't explain why you get different outputs after compiling a different version. Maybe it partly uses system and local libraries, which would result in a linking mess indeed.

To further investigate the issue try to see exactly which libraries are found. If you can add the following after ```find_package(Boost)``` in ```tudatBundle/tudat/Tudat/CMakeLists.txt```.

```
foreach(Component ${BoostComponents})
  string(TOUPPER "${Component}" ComponentUpper)
  message(STATUS "${ComponentUpper}: ${Boost_${ComponentUpper}_FOUND} - ${Boost_${ComponentUpper}_LIBRARY}")
endforeach()
```
This should output exactly which libraries it find and where! Can you post the new cmake output here?

You can also drop by the office hours on Thursday. Thanks!

**Comment by jgutierrezahum** [comment] 2017-02-28 19:44
Hi Jacco,

Thanks for the help. In the CMakeLists.txt file you mention I did not find just a find_package(Boost) but the following line instead:

`find_package(Boost 1.45.0 COMPONENTS date_time system unit_test_framework filesystem regex REQUIRED)`

In any case, I added those lines and run make again and I got the output I attach. It seems like it does detect six libraries (thread, date_time, system, unit_test_framework, filesystem, regex), but please take a look at the output yourself. I will drop by for the office hours if there is no easy solution. Thanks in advance!

For some reason GitHub does not let me attach the file. I thus attach the output log below:

`Running "/usr/bin/cmake '/home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle' '-GCodeBlocks - Unix Makefiles' -DCMAKE_CXX_COMPILER:STRING=/usr/bin/g++ -DCMAKE_C_COMPILER:STRING=/usr/bin/gcc -DCMAKE_PREFIX_PATH:STRING=/usr -DQT_QMAKE_EXECUTABLE:STRING=/usr/lib/x86_64-linux-gnu/qt4/bin/qmake" in /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/build-tudat_bundle-Desktop-Default.
-- /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle
-- BOOST: Using gnu.
-- Build boost (note that this may take a while, please sit back)
--   ./b2;--user-config=cmake-config.jam;link=static,shared;threading=multi;--build-dir=Build;stage;-sNO_BZIP2=1;variant=release;--layout=tagged;toolset=gcc;--with-filesystem;--with-system;--with-thread;--with-regex;--with-date_time;--with-test
-- Building CSpice from within TudatBundle.
-- WARNING: building release version!
-- Building NRLMSISE00 from within TudatBundle.
-- WARNING: building release version!
-- << Tudat (Release - part of TudatBundle) >>
-- CMake Module path(s): /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/external/CMake;/home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/tudat/Tudat/External/CMake
-- Using gnucxx compiler.
-- Building with flags: -Wall -std=c++11 -Wextra -Wno-unused-parameter -Woverloaded-virtual -Wold-style-cast -Wnon-virtual-dtor.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   date_time
--   system
--   unit_test_framework
--   filesystem
--   regex
-- FILESYSTEM: ON - /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_filesystem-mt.a
-- SYSTEM: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_system.a;debug;/home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_system-mt.a
-- THREAD: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_thread.a;debug;/home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_thread-mt.a
-- REGEX: ON - /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_regex-mt.a
-- DATE_TIME: ON - optimized;/usr/lib/x86_64-linux-gnu/libboost_date_time.a;debug;/home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_date_time-mt.a
-- UNIT_TEST_FRAMEWORK: ON - /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/boost/stage/lib/libboost_unit_test_framework-mt.a
-- SPICE enabled!
-- SPICE_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/cspice/lib/libcspice.a
-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/nrlmsise-00/lib/libnrlmsise00.a
-- GSL disabled!
-- Building SatellitePropagatorExamples from within TudatBundle.
-- Relative path (wrt to project): /tudatExampleApplications/satellitePropagatorExamples/SatellitePropagatorExamples
-- WARNING: building release version!
-- Using gnucxx compiler.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   unit_test_framework
--   filesystem
--   regex
-- SPICE_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/cspice/lib/libcspice.a
-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/nrlmsise-00/lib/libnrlmsise00.a
-- Building TemplateApplication from within TudatBundle.
-- Relative path (wrt to project): /tudatExampleApplications/templateApplication/TemplateApplication
-- WARNING: building release version!
-- Using gnucxx compiler.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   unit_test_framework
--   filesystem
--   regex
-- SPICE_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/cspice/lib/libcspice.a
-- NRLMSISE-00 enabled!
-- NRLMSISE00_LIBRARIES: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/tudat_bundle/nrlmsise-00/lib/libnrlmsise00.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jagutierrez/Documents/MScFirstYear/Space Project Tudat/build-tudat_bundle-Desktop-Default
`

**Comment by magnific0** [comment] 2017-03-01 09:45
Hi @jgutierrezahum, thanks for posting the new output. This is indeed the line I mean. As I expected you have a mix of local and system libraries that are being found, which explains the mess. Now we should look into why it doesn't prefer local libraries over system ones, as we kindly force it to do. It is best to look at this together during the office hours. 

For now, if you could uninstall the libboost-dev package, without breaking any dependencies, you should probably be okay to continue working. Please repost the cmake output log after you have removed the package. Indeed GitHub doesn't allow .log attachements, but you can rename it .txt and it will work!

**Comment by jgutierrezahum** [comment] 2017-03-01 10:14
Hi @magnific0, thanks for the answer. I've removed both libboost-dev and I think nothing changed (cmake-output-log.txt), the building process still threw the same error.

I've also uninstalled libboost1.58-dev and now the cmake throws errors (cmake-output-log2.txt). It seems to not be able to detect any version of boost anymore, but shouldn't it download it again in that case?
[cmake-output-log2.txt](https://github.com/Tudat/tudat/files/810326/cmake-output-log2.txt)

In any case I'll drop by the office tomorrow.

p.s. Weirdly enough it was not letting me upload txt or even zip files either. I guess it was just my Internet connection as it works now.


[cmake-output-log.txt](https://github.com/Tudat/tudat/files/810317/cmake-output-log.txt)

**Comment by magnific0** [comment] 2017-03-01 10:41
Hi @jgutierrezahum, thanks for the response. Let's look at it tomorrow in more detail. The CMake errors should likely be resolved by deleting your CMakeCache.txt. As it is looking for files in old removed locations.

**Comment by jgutierrezahum** [comment] 2017-03-02 12:21
Dear Jacco,

I tried deleting the cache and it indeed worked. The installation of tudat worked as well and the unit tests were succesful. I'm afraid I cannot make it to the open office hours since I have a meeting at the moment. If you think it is still necessary, I can make it the next time or at other time.

Thanks,

Jose
________________________________________

**Comment by magnific0** [comment] 2017-03-08 12:22
We just tested the new ```add_boost.cmake``` on @jgutierrezahuma's system and it fixes the problem, also if system libraries of boost are installed on the system. So another reason to merge:
https://github.com/Tudat/tudatBundle/pull/11

**Closed by magnific0** 2017-03-08 12:22 UTC
Labels: Linux
