### ISSUE TITLE
Multiple Tests related to orbit determination fail (e.g., test_*Partials)

### ISSUE THREAD

**Issue by Sceki** [Tudat/tudat#295] opened 2017-11-16 11:10 UTC
I have a MacBook Pro, macOs Sierra version 10.12.6. I have an error while running the test:
"Errors while running CTest
make: *** [test] Error 8
12:27:57: The process "/Applications/CMake.app/Contents/bin/cmake" exited with code 2.
Error while building/deploying project TudatBundle (kit: Desktop)
When executing step "CMake Build" ".
I am Giacomo Acciarini, from the course Numerical Astrodynamics.

**Comment by DominicDirkx** [comment] 2017-11-16 11:33
@Sceki On the wiki, there is a list of files that we need to understand what is going on, please post those as well.

**Comment by Sceki** [comment] 2017-11-16 19:10
Thanks for your answer!
Sorry but what is the wiki?

**Comment by DominicDirkx** [comment] 2017-11-16 19:24
I mean our website: tudat.tudelft.nl. It's at the end our installation guide.

**Comment by Sceki** [comment] 2017-11-16 19:28
ok. 
I reached the step 5 of the point 3 in the installation guide. But I didn't remove the word "test" and I didn't press the hammer since I had those errors.

**Comment by DominicDirkx** [comment] 2017-11-16 20:00
Ok.... Read step 5 and please follow the instructions on what to do after one or more tests fail.

**Comment by Sceki** [comment] 2017-11-17 08:27
This is my file lasttest.log:
[LastTest.log](https://github.com/Tudat/tudat/files/1481559/LastTest.log)

**Comment by DominicDirkx** [comment] 2017-11-17 08:43
@Sceki  There seems to be quite a lot failing for you, but in most cases the failures seem to be due to a common origin (in particular related to Eigen functionality). Could you post a screenshot of yout Project->Build&Run->Build screen:

![image](https://user-images.githubusercontent.com/5039068/32938129-729fe30c-cb7b-11e7-9735-3ead69f45704.png)

Also, could you run the following example applications:

application_ApolloEntry
application_ApolloEntryJSON
application_VariationalEquationsPropagator
application_SinglePerturbedSatellitePropagator

And let us know if they run properly?

An explanation on how to run them is given here:

http://tudat.tudelft.nl/installation/configureTudatLibraries.html

In step 6. Also:

" After running the unit tests, make sure to remove the ‘test’ text that you’ve typed in the project tab. "

If you come to the lecture today, we will try to make some time for you afterwards to looko at this problem, at least to diagnose if it will impact your ability to do the assignments.

**Comment by Sceki** [comment] 2017-11-17 11:37
These are the screens:
<img width="1440" alt="schermata 2017-11-17 alle 12 29 47" src="https://user-images.githubusercontent.com/33602846/32945274-0df95e8e-cb93-11e7-9b9d-ffe363600c68.png">
<img width="1440" alt="schermata 2017-11-17 alle 12 29 47" src="https://user-images.githubusercontent.com/33602846/32945277-0f235fe4-cb93-11e7-9bf8-e311929afa2a.png">

I removed the "test" word!
And running the aforesaid 4 applications I have these results:
<img width="1112" alt="schermata 2017-11-17 alle 12 36 32" src="https://user-images.githubusercontent.com/33602846/32945512-04597f66-cb94-11e7-99c5-a3d6fc43c807.png">
<img width="1127" alt="schermata 2017-11-17 alle 12 35 45" src="https://user-images.githubusercontent.com/33602846/32945514-076112f0-cb94-11e7-8583-47911768dadd.png">
<img width="1099" alt="schermata 2017-11-17 alle 12 34 41" src="https://user-images.githubusercontent.com/33602846/32945524-0b33fa46-cb94-11e7-93cc-ba287ae82ec2.png">
<img width="1127" alt="schermata 2017-11-17 alle 12 35 45" src="https://user-images.githubusercontent.com/33602846/32945535-1616c1fa-cb94-11e7-9e5f-6c6aa98ef94e.png">

I am coming anyway today!

**Comment by Sceki** [comment] 2017-11-17 11:39
<img width="1085" alt="schermata 2017-11-17 alle 12 33 40" src="https://user-images.githubusercontent.com/33602846/32945600-5a6ad2ce-cb94-11e7-8491-4eaca10b62ab.png">

**Comment by DominicDirkx** [comment] 2017-11-17 11:43
@Sceki Thanks for the quick reply. This all looks good, these seem to give the output they're supposed to. I think there's a good chance these failures won't affect your ability to do the assignments, but we'll have a better look this afternoon.

**Comment by Sceki** [comment] 2017-11-17 11:46
Ok! Thank you very much for your help!

**Comment by magnific0** [comment] 2017-11-19 16:58
I am mentioning the tests here so that people can find this issue more easily

    test_AngularPositionModel
test_PositionObservationModel
test_TidalPropertyEstimation
test_SphericalHarmonicPartials
test_OneWayRangePartials
test_NWayRangePartials
test_OneWayDifferencedRangePartials
test_OneWayDopplerPartials
test_TwoWayDopplerPartials
test_AngularPositionPartials
test_LightTimeCorrectionPartials
test_VariationalEquations

**Comment by DominicDirkx** [comment] 2017-11-19 17:02
Small update: it looks like this is a result of compilation with debugging symbols on. Of course, this should not be a problem, and I'll see if I can reproduce this issue.

@Sceki Have you gone through the steps we discussed on Friday to fix this for you?

**Comment by DominicDirkx** [comment] 2017-11-19 17:14
When compiling in Debug mode, it seems like these also occur for me. Looks like they're all small issues, we'll get to fixing them in the coming weeks.

@Sceki  Nevertheless, make sure you do not compile/run in debug mode. These may prevent the code for your assignments from running. Even if it doesn't, your code will be very slow.

**Comment by Sceki** [comment] 2017-11-19 18:27
Ok. Thank you very much!
________________________________
Da: DominicDirkx [notifications@github.com]
Inviato: domenica 19 novembre 2017 18.14
A: Tudat/tudat
Cc: Giacomo Acciarini; Mention
Oggetto: Re: [Tudat/tudat] Multiple Tests related to orbit determination fail (e.g., test_*Partials) (#295)


When compiling in Debug mode, it seems like these also occur for me. Looks like they're all small issues, we'll get to fixing them in the coming weeks.

@Sceki<https://github.com/sceki> Nevertheless, make sure you do not compile/run in debug mode. These may prevent the code for your assignments from running. Even if it doesn't, your code will be very slow.

**Comment by Sceki** [comment] 2017-11-19 18:30
Anyway I did not go through the steps we discussed, because I understood that I should be able to do the first assignments in any case. Could you please tell me the steps again so that I can do it now, if it is useful?

**Comment by DominicDirkx** [comment] 2017-11-20 07:24
All unit test failures have been resolved with the latest commits.

@Sceki Delete your build folders, delete your CMakeLists.txt.user file, make sure that your build setting is set to Default or Release (and not Debug), close Qt, repopen and recompile.

In the future, please write down answers that you will need later. I do not appreciate having to spend time answering the same question by the same person multiple time.

**Closed by DominicDirkx** 2017-11-20 07:24 UTC
Labels: Mac OS X, unit test
