### ISSUE TITLE
New application: "undefined reference to 'init_unit_test_suite(int, char**)'"

### ISSUE THREAD

**Issue by BeatrizMOliveira** [Tudat/tudat#143] opened 2017-02-21 11:06 UTC
I tried adding new applications to the project. Now I get this error:
![screenshot 2017-02-21 12 10 38](https://cloud.githubusercontent.com/assets/25655772/23162406/2887e650-f82e-11e6-879c-e2168eecb663.png)

**Comment by magnific0** [comment] 2017-02-21 16:16
Hi @BeatrizMOliveira,
That seems like it is unrelated to your application. So just to be sure, can you push your code to your private repository and invite me.
Jacco

**Comment by magnific0** [comment] 2017-02-21 16:25
@BeatrizMOliveira, just a quick follow up: are you confident the error comes from compiling only your application? Instead of pushing to GitHub you can also post your ```MyApplication/CMakeLists.txt``` and the top part of your application that contains all the ```#include``` statements in the issue here.
From the looks of it, the error is caused by an application trying to use Boost unit test framework code (e.g. ```#include<boost/test/unit_test.hpp>``` without properly linking the library).

**Comment by BeatrizMOliveira** [comment] 2017-02-21 17:46
[CMakeLists.txt](https://github.com/Tudat/tudat/files/790963/CMakeLists.txt)
#include <Tudat/SimulationSetup/tudatSimulationHeader.h>

**Comment by DominicDirkx** [comment] 2017-02-21 17:48
There doesn't seem to be any new application in the CMakeLists. 

Which steps did you take to try to add an application to the project?

**Comment by BeatrizMOliveira** [comment] 2017-02-21 18:12
I removed the comments from the entries for the Solution (after creating a file with the name)

**Comment by BeatrizMOliveira** [comment] 2017-02-21 18:35
I think it's been solved.

**Comment by magnific0** [comment] 2017-02-22 07:48
Great to hear! What was the solution?

**Comment by BeatrizMOliveira** [comment] 2017-02-22 14:00
Honestly, I don't know. Importing a new instance of the application to clean up the code and I stopped getting the error.

**Comment by magnific0** [comment] 2017-02-22 14:18
Alright, great! I'm closing the issue then.

**Closed by magnific0** 2017-02-22 14:18 UTC
