### ISSUE TITLE
Failed Unit Test - test_UnscentedKalmanFilter; Windows 10

### ISSUE THREAD

**Issue by KapishAggarwal** [Tudat/tudat#452] opened 2018-11-11 18:43 UTC
Failed Unit Test - test_UnscentedKalmanFilter; Windows 10
[LastTest.log](https://github.com/Tudat/tudat/files/2569699/LastTest.log)

**Comment by DominicDirkx** [comment] 2018-11-12 08:31
Duplicate of #451

**Closed by DominicDirkx** 2018-11-12 08:31 UTC
